name: Run Postman Tests with Newman

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # You can adjust the version if needed

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection with Environment
        run: newman run Restful-Booker.postman_collection.json -e "Test Environment.postman_environment.json"
